# Generated by Django 4.1.2 on 2022-10-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaosocial', models.TextField(max_length=100, verbose_name='razaosocial')),
                ('cnpj', models.TextField(max_length=500, verbose_name='cnpj')),
                ('gerenteresponsavel', models.TextField(max_length=500, verbose_name='gerenteresponsavel')),
                ('telempresa', models.TextField(verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
