# Generated by Django 4.1.2 on 2022-11-26 16:46

import aplic.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numcontrato', models.CharField(max_length=20, verbose_name='Numero do Contrato')),
                ('servicocontratado', models.TextField(max_length=100, verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logadouro', models.CharField(max_length=50, verbose_name='Rua,Avenida')),
                ('cep', models.CharField(max_length=9, verbose_name='Cep')),
                ('uf', models.CharField(max_length=2, verbose_name='Uf')),
                ('numestabelecimento', models.CharField(max_length=6, verbose_name='N°')),
            ],
            options={
                'verbose_name': 'Reunião',
                'verbose_name_plural': 'Reunião',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desenvolvedorlider', models.CharField(max_length=30, verbose_name='Lider')),
                ('desenvolvedoresauxiliares', models.CharField(max_length=30, verbose_name='Auxilíares')),
                ('imagem', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=aplic.models.get_file_path, variations={'thumb': {'crop': True, 'height': 260, 'width': 420}}, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horamanutencao', models.CharField(max_length=10, verbose_name='Horário de manutenção')),
                ('desenvolvedorresponsavel', models.CharField(max_length=30, verbose_name='Desenvolvedor Responsável')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaosocial', models.CharField(max_length=20, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('especificacoesdoservico', models.CharField(max_length=200, verbose_name='Especificações do Serviço')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=aplic.models.get_file_path, variations={'thumb': {'crop': True, 'height': 260, 'width': 420}}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(max_length=14, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='gerenteresponsavel',
            field=models.CharField(max_length=30, verbose_name='Gerente Responsavel'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razaosocial',
            field=models.CharField(max_length=20, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telempresa',
            field=models.CharField(max_length=12, verbose_name='Telefone'),
        ),
    ]
