# Generated by Django 4.1.2 on 2022-11-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_contrato_endereco_funcionario_manutencao_servico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, verbose_name='Twitter'),
        ),
    ]
